using KOF.RouteMap.Domain.Common;

namespace KOF.RouteMap.Domain.Entities;

public class VisitPlan 
{
    public int Id { get; set; }
    public string? NroCliente { get; set; }
    public string? NombreCliente { get; set; }
    public string? NombreCliente2 { get; set; }
    public string? NombreCliente3 { get; set; }
    public string? ConcBusq { get; set; }
    public string? OrganizacaoVendas { get; set; }
    public string? CanalDistribucion { get; set; }
    public string? Sector { get; set; }
    public string? EstatusCliente { get; set; }
    public string? FechaAltaSistema { get; set; }
    public string? CreadoPor { get; set; }
    public string? ModalidadVentas { get; set; }
    public string? IDPlanVisita { get; set; }
    public string? InicioVigenciaPlan { get; set; }
    public string? FinVigenciaPlan { get; set; }
    public string? Ruta { get; set; }
    public string? TipoPlanVisita { get; set; }
    public string? MetodoVenta { get; set; }
    public string? InactivoVisitaPlan { get; set; }
    public string? Ritmo { get; set; }
    public string? FechaInicioContacto { get; set; }
    public string? FechaFinalContacto { get; set; }
    public string? VisitaLunes { get; set; }
    public string? Lun_de { get; set; }
    public string? Lun_a { get; set; }
    public string? VisitaMartes { get; set; }
    public string? Mar_de { get; set; }
    public string? Mar_a { get; set; }
    public string? VisitaMiercoles { get; set; }
    public string? Mie_de { get; set; }
    public string? Mie_a { get; set; }
    public string? VisitaJueves { get; set; }
    public string? Jue_de { get; set; }
    public string? Jue_a { get; set; }
    public string? VisitaViernes { get; set; }
    public string? Vie_de { get; set; }
    public string? Vie_a { get; set; }
    public string? VisitaSabado { get; set; }
    public string? Sab_de { get; set; }
    public string? Sab_a { get; set; }
    public string? VisitaDomingo { get; set; }
    public string? Dom_de { get; set; }
    public string? Dom_a { get; set; }
    public string? Dia_de { get; set; }
    public string? Mes_de { get; set; }
    public string? Anio_de { get; set; }
    public string? Dia_a { get; set; }
    public string? Mes_a { get; set; }
    public string? VisitasProg { get; set; }
    public string? FrecuenciaVisita { get; set; }
    public string? SplitPedidosPE { get; set; }
    public string? PrevEspecializada { get; set; }
    public string? Calle { get; set; }
    public string? ContinuacionCalle { get; set; }
    public string? Colonia { get; set; }
    public string? NoExterno { get; set; }
    public string? NoInterno { get; set; }
    public string? EntreCalle { get; set; }
    public string? yCalle { get; set; }
    public string? Delegacion { get; set; }
    public string? CP { get; set; }
    public string? Baja { get; set; }
    public string? CalleDomfiscal { get; set; }
    public string? Email { get; set; }
    public string? Pais { get; set; }
    public string? PoblacionDomfiscal { get; set; }
    public string? NoDomfiscal { get; set; }
    public string? Region { get; set; }
    public string? DescRegion { get; set; }
    public string? RegionDomfiscal { get; set; }
    public string? ColoniaDomfiscal { get; set; }
    public string? ClaseImpuesto { get; set; }
    public string? NIF_CUIT_RFC { get; set; }
    public string? Imp2 { get; set; }
    public string? TipoCobro { get; set; }
    public string? TipoNIF { get; set; }
    public string? ViasPago { get; set; }
    public string? CuentaAsociada { get; set; }
    public string? GrupoImputacion { get; set; }
    public string? GrupoTesoreria { get; set; }
    public string? EsquemaCliente { get; set; }
    public string? NoCteAnt { get; set; }
    public string? Coord_X { get; set; }
    public string? Coord_Y { get; set; }
    public string? GpoCuentas { get; set; }
    public string? localidad { get; set; }
    public string? PersonaContacto { get; set; }
    public string? NombrePersConta { get; set; }
    public string? ApellidoPersCon { get; set; }
    public string? Telefono { get; set; }
    public string? TelWhatsapp { get; set; }
    public string? TelefonMovil { get; set; }
    public string? Fax { get; set; }
    public string? TelExt { get; set; }
    public string? TelefonoPersContac { get; set; }
    public string? Estado { get; set; }
    public string? DescripcionEstado { get; set; }
    public string? RevenueMap { get; set; }
    public string? RegionKOF { get; set; }
    public string? DescripcionRegionKOF { get; set; }
    public string? ZonaVentas_UO { get; set; }
    public string? GerenciaVentas { get; set; }
    public string? JefaturaVentas { get; set; }
    public string? RegionDistribucion { get; set; }
    public string? CentroSuministro { get; set; }
    public string? CondicionExpedic { get; set; }
    public string? TipoServicio { get; set; }
    public string? DescripcionTipoSer { get; set; }
    public string? ZonaTransporte { get; set; }
    public string? IDMulticentroMultiruta { get; set; }
    public string? PrioEntrega { get; set; }
    public string? ClaseDocVentas { get; set; }
    public string? CondPago { get; set; }
    public string? BloqueoPedido { get; set; }
    public string? BloqPedVtaSe { get; set; }
    public string? BloqEntregaTodasAreas { get; set; }
    public string? BloqEntVtaSe { get; set; }
    public string? BloqFacturatodasAreas { get; set; }
    public string? BloqFacVtaSe { get; set; }
    public string? BloqSoporteVentas { get; set; }
    public string? TipoDetallista { get; set; }
    public string? DescripcionTipoDet { get; set; }
    public string? Condicion { get; set; }
    public string? DescripcionCondicio { get; set; }
    public string? ClienteICEKOF { get; set; }
    public string? CtaClave { get; set; }
    public string? Cadena { get; set; }
    public string? ContratodePreferen { get; set; }
    public string? UnidadNegocio { get; set; }
    public string? SubUnidadNegocio { get; set; }
    public string? GrupoCanal { get; set; }
    public string? DescGrupoCanal { get; set; }
    public string? Canal { get; set; }
    public string? DescCanal { get; set; }
    public string? CanalKOF { get; set; }
    public string? DescCanalKOF { get; set; }
    public string? GEC { get; set; }
    public string? DescGEC { get; set; }
    public string? NivSocioeconomico { get; set; }
    public string? DescripcionNSE { get; set; }
    public string? NivSocPlanchado { get; set; }
    public string? DescripciponNSEP { get; set; }
    public string? NivelMargen { get; set; }
    public string? SegPrecios { get; set; }
    public string? DescSegPrec { get; set; }
    public string? SegDescuentos { get; set; }
    public string? DescSegDesc { get; set; }
    public string? SegPortafolio { get; set; }
    public string? DescSegPort { get; set; }
    public string? SegPropuestaValor { get; set; }
    public string? DescSegPDV { get; set; }
    public string? SegPeliculaExito { get; set; }
    public string? DescSegPDE { get; set; }
    public string? SegExhibicion { get; set; }
    public string? DescSegExh { get; set; }
    public string? SegComunicacion { get; set; }
    public string? DescSegCom { get; set; }
    public string? OcasionConsumo { get; set; }
    public string? DescOcasionConsumo { get; set; }
    public string? Foco { get; set; }
    public string? DescCategoriaFoco { get; set; }
    public string? GerReg { get; set; }
    public string? LimiteCred { get; set; }
    public string? ClusterAnalytics { get; set; }
    public string? DescClusterAnalytics { get; set; }
    public string? IT { get; set; }
    public string? DescIT { get; set; }
    public string? NivelColaboracion { get; set; }
    public string? Imagen { get; set; }
    public string? Delivery { get; set; }
    public string? Enrejado { get; set; }
    public string? Tamano { get; set; }
    public string? DescTamano { get; set; }
    public string? Localidad1 { get; set; }
    public string? Fe_baja { get; set; }
    public string? Ciudad2 { get; set; }
    public string? Distrito { get; set; }
    public string? Secuencia { get; set; }
    public string? NumeroIdentificacionFiscal { get; set; }
    public string? IdLoc { get; set; }
    public string? DatosAdicionales { get; set; }
    public string? DomicilFiscal { get; set; }
    public string? McDonalds { get; set; }
    public string? MaterialUnico { get; set; }
    public string? InVoice { get; set; }
    public string? ClienteEDI { get; set; }
    public string? IndicadorCompen { get; set; }
    public string? IndicadorAyudan { get; set; }
    public string? IndicadorRutDir { get; set; }
    public string? Agrupamiento { get; set; }
    public string? FechaAlta { get; set; }
    public string? Telvendedor { get; set; }
    public string? NombreTelvendedor { get; set; }
    public string? JefeTelvendedor { get; set; }
    public string? NombreJefeTelvendedor { get; set; }
    public string? IntensidadCompetitiva { get; set; }
    public string? ShareKof { get; set; }
    public string? TamanoFisico { get; set; }
    public string? BloqueoPromociones { get; set; }
    public string? DescBloqueoPromo { get; set; }
    public string? DescShareKof { get; set; }
    public string? DescIntensidadComp { get; set; }
    public string? CallPrevenda { get; set; }
    public string? SectorIndustrial { get; set; }
    public string? PrestamoPalletChapatex { get; set; }
}